README.md, pom.xml, src/main/arm/deploy.azcli, src/main/arm/mainTemplate.json, src/main/resources/README.md, src/main/scripts/install.sh, src/main/scripts/virtualimage.properties, src/main/scripts/was-check.sh
This PR is to resolve the following 3 issues:
* Issue #1 
* Issue #3 
* Issue #7 
* add entitlement check and patch using cloud-init
*  parameterize tWAS installation properties
* upgrade to RHEL 8_3
* add a new data disk to increase disk space  which is required to install tWAS
* install latest tWAS and jdk version
* update readme
* retrieve device name dynamically instead of hard-coded one
=> Support entitlement check and patch

.github/workflows/build.yml, README.md, test/mainTemplate.json
**The major steps in workflow**
-- Verify that no deployment failure using latest generated image
-- Verify that IBM environment will be removed after deployment with untitled IBM account
-- Generate SAS urls for creating image offer
-- Send notification to Teams channel
**Update mainTemplate.json**
-- To adopt workflow changes, allow passed in Storage Account and Vm name for visibility
**Update README**
-- To describe steps of creating image offer using SAS urls generated by workflow and the post actions after it.
Based on https://github.com/WASdev/azure.websphere-traditional.image/pull/16/commits/68cb0c6d5c9a94740565b01dab218c42f70781be
new file:   .github/workflows/build.yml
- Add comments to address @git4rk concerns.
- Remove
-  userEmail: ${{ secrets.USER_EMAIL }}
- make `vmAdminId` …
=> Based on Zheng's commit 68cb0c6

ihs/src/main/scripts/was-check.sh, ihs/test/mainTemplate.json, twas-nd/src/main/scripts/was-check.sh, twas-nd/test/mainTemplate.json
This is the 1st PR to address https://github.com/WASdev/azure.websphere-traditional.cluster/issues/43.
The 2nd PR is issued to cluster repo: https://github.com/WASdev/azure.websphere-traditional.cluster/pull/45
Local testing is passed before sending out the PR.
=> Use space to separate IBMid credential

README.md
modified:   README.md
- Add link to issue tracker.
Signed-off-by: Ed Burns <edburns@microsoft.com>
=> On branch master - Add link to issue tracker.

.github/workflows/ihsBuild.yml, .github/workflows/twas-ndBuild.yml, ihs/src/main/scripts/install.sh, ihs/src/main/scripts/virtualimage.properties, ihs/src/main/scripts/was-check.sh, twas-nd/src/main/scripts/install.sh, twas-nd/src/main/scripts/virtualimage.properties, twas-nd/src/main/scripts/was-check.sh
This is the 1st PR for image repo to partially fix the following issues:
* WASdev/azure.websphere-traditional.cluster/issues/56
* WASdev/azure.websphere-traditional.cluster/issues/85
* WASdev/azure.websphere-traditional.cluster/issues/39
The 2nd PR to completely fix the above issues will be sent out later to the cluster repo.
=> Fix issues 39, 56 and 85

README.md, ihs/README.md, twas-nd/README.md
=> rewording the reference to ihs readme

ihs/src/main/cli/deploy.azcli, twas-nd/src/main/cli/deploy.azcli
This is a side PR related to part of @git4rk 's review comments of WASdev/azure.liberty.aro/pull/4.
=> Small refactoring for deploy.azcli

.github/workflows/ihsBuild.yml, .github/workflows/twas-ndBuild.yml
Add repository dispatch type to tighten the trigger.
Closing #50 and create this to correct the default branch from **master** to **main**
Signed-off-by: Zheng Chang <zhengchang@microsoft.com>
=> Add trigger typ to repository_dispatch

ihs/src/main/scripts/install.sh, twas-nd/src/main/scripts/install.sh
The PR is to fix WASdev/azure.websphere-traditional.cluster/issues/125.
=> Fix im files permission denied issue

.github/workflows/entitlement-check.yml
The PR is to set up a pipeline to verify if the entitlement check works for an **entitled** IBMid configured in GitHub secrets.
More background information can be found from WASdev/azure.websphere-traditional.cluster/issues/56.
See the successful build [Entitlement check](https://github.com/majguo/azure.websphere-traditional.image/actions/runs/1896440726).
--------------
Signed-off-by: Jianguo Ma jiangma@microsoft.com
=> Create GitHub Actions workflow to verify if entitlement check works

.github/workflows/ihsBuild.yml, .github/workflows/twas-baseBuild.yml, .github/workflows/twas-ndBuild.yml, ihs/pom.xml, ihs/src/main/scripts/install.sh, twas-base/pom.xml, twas-base/src/main/scripts/install.sh, twas-nd/pom.xml, twas-nd/src/main/scripts/install.sh
This PR is to resolve WASdev/azure.websphere-traditional.cluster/issues/155 by enhancing the current base image pipelines with:
* Updated package and applied iFixes after installation of twas-nd, twas-base and ihs
* Failed fast if installation failed
* Added log and dumped to pipeline run for facilitating troubleshooting
See the following pipeline runs with the expected results:
* [twas-base](https://github.com/majguo/azure.websphere-traditional.image/actions/runs/2039277505): succeeded, installation log dumped
* [twas-nd](https://github.com/majguo/azure.websphere-traditional.image/actions/runs/2039277503): succeeded, installation log dumped
* [ihs](https://github.com/majguo/azure.websphere-traditional.image/actions/runs/2039277504): failed fast when ihs installation failed during VM …
=> Enhance the current base image pipelines

docs/howto-access-source-vm.md
The PR is to resolve WASdev/azure.websphere-traditional.cluster/issues/156 by creating a how-to guide about access the source VM for issue triage.
=> how-to guide on source vm access

.github/workflows/entitlement-check.yml, .github/workflows/ihsBuild.yml, .github/workflows/twas-baseBuild.yml, .github/workflows/twas-ndBuild.yml, config.properties, ihs/README.md, ihs/src/main/arm/mainTemplate.json, twas-base/README.md, twas-base/src/main/arm/mainTemplate.json, twas-nd/README.md, twas-nd/src/main/arm/mainTemplate.json
The PR is to resolve WASdev/azure.websphere-traditional.cluster/issues/161.
From the following runs of twas-nd CICD and twas-base CICD, the reported issue is fixed:
* https://github.com/majguo/azure.websphere-traditional.image/actions/runs/2518711391
* https://github.com/majguo/azure.websphere-traditional.image/actions/runs/2518711090
Note: the above two pipeline runs failed due to the failure of the entitlement check, see [this](https://github.com/WASdev/azure.websphere-traditional.image/actions/runs/2518767923) and the relevant [reported issue](https://github.com/WASdev/azure.websphere-traditional.cluster/issues/162). 
=> Update api version and arm-ttk version

ihs/src/main/resources/marketing-artifacts/partner-center.html, twas-base/src/main/resources/marketing-artifacts/partner-center.html, twas-nd/src/main/resources/marketing-artifacts/partner-center.html
This PR includes updates for the following.
1. IBM Marketing recommended names for the offerings.
2. IBM ID team review comments.
=> BVN: Update names and ID teams comments

.github/workflows/ihsBuild.yml, .github/workflows/twas-baseBuild.yml, .github/workflows/twas-ndBuild.yml
modified:   .github/workflows/ihsBuild.yml
modified:   .github/workflows/twas-ndBuild.yml
=> On branch ibm-202-fix-curl-examples

.github/workflows/ihsBuild.yml, .github/workflows/twas-baseBuild.yml, .github/workflows/twas-ndBuild.yml
modified:   .github/workflows/ihsBuild.yml
modified:   .github/workflows/twas-ndBuild.yml
=> On branch edburns-msft-ibm-247-revert-use-of-automatic-publishing

.github/workflows/ihsBuild.yml, .github/workflows/twas-baseBuild.yml, .github/workflows/twas-ndBuild.yml, ihs/pom.xml, twas-base/pom.xml, twas-nd/pom.xml
modified:   .github/workflows/ihsBuild.yml
modified:   .github/workflows/twas-ndBuild.yml
=> On branch edburns-msft-ibm-312-re-apply-automatic-publishing

ihs/src/main/resources/marketing-artifacts/README.md, twas-nd/src/main/resources/marketing-artifacts/README.md
modified:   ihs/src/main/resources/marketing-artifacts/README.md
modified:   twas-nd/src/main/resources/marketing-artifacts/README.md
=> On branch edburns-msft-ibm-344-dependabot-scan-mitigation

.github/workflows/setup-credentials.sh, README.md, docs/howto-update-image.md
…
modified:   README.md
modified:   docs/howto-update-image.md
=> On branch edburns-msft-ibm-342-end-to-end-automation-documentation Refine information architecture and explain automation.

ihs/pom.xml, ihs/src/main/arm/mainTemplate.json, twas-base/pom.xml, twas-base/src/main/arm/mainTemplate.json, twas-nd/pom.xml, twas-nd/src/main/arm/mainTemplate.json
modified:   ihs/pom.xml
modified:   ihs/src/main/arm/mainTemplate.json
modified:   twas-base/pom.xml
modified:   twas-base/src/main/arm/mainTemplate.json
modified:   twas-nd/pom.xml
modified:   twas-nd/src/main/arm/mainTemplate.json
=> On branch edburns-msft-ibm-394-remove-mainTemplateJsonComments

README.md, docs/howto-update-apiVersions.md
modified:   README.md
new file:   docs/howto-update-apiVersions.md
=> On branch edburns-msft-431-document-apiVersion Document how to update apiVersions.

ihs/pom.xml, twas-base/pom.xml, twas-nd/pom.xml
Closes https://github.com/WASdev/azure.websphere-traditional.image/issues/95
=> Update azure-javaee-iaas-parent version to 1.0.19

docs/howto-update-apiVersions.md, docs/howto-update-image.md
For https://dev.azure.com/was-azure/was-azure/_workitems/edit/445
=> Update doc based on 9.0.5.17 learning

twas-base/pom.xml
For issue https://github.com/WASdev/azure.websphere-traditional.singleserver/issues/93
=> Update for tWAS 9.0.5.18

ihs/pom.xml, twas-nd/pom.xml
For https://github.com/WASdev/azure.websphere-traditional.cluster/issues/234
=> Update IHS and ND images to 9.0.5.18

utilities/oscap.sh
The PR is to resolve #101. 
The pipelines in my fork ran successfully with the change:
* [ihs CICD](https://github.com/majguo/azure.websphere-traditional.image/actions/runs/7259756819)
* [twas-nd CICD](https://github.com/majguo/azure.websphere-traditional.image/actions/runs/7258744152)
* [twas-base CICD](https://github.com/majguo/azure.websphere-traditional.image/actions/runs/7258728106)
=> Disable swap

docs/howto-update-crm-connection.md
…
docs/howto-update-crm-connection.md
=> On branch edburns-msft-ibm-558-document-crm-connection Describe how to get connection string and where to save it.
