WASdev/azure.websphere-traditional.image

.github/workflows/build.yml
An entitled IBMid must be provided to install tWAS while provisioning the VM which is used for creating VM base image.
@zhengchang907 will enhance test cases by adding tWAS installation directory check in another PR.
=> Provide an entitled IBMid while provisioning VM

.github/workflows/build.yml, README.md, src/main/scripts/install.sh
The latest run of pipeline failed. During my investigation, I found that it failed due to it hangs at execution of  extension script, especially the following step when executing `yum update -y`:
* ![image](https://user-images.githubusercontent.com/10357495/118822185-85b4aa80-b8ea-11eb-9bae-bd0e20a7d35e.png)
The WALinuxAgent is the agent to execute the extension script, so it's obvious that it may cause issue if WALinuxAgent is upgraded during the execution of extension script.
The solution of the PR is moving `yum update` from extension script to pipeline.
=> Move yum update from extension script to pipeline

pom.xml, src/main/arm/mainTemplate.json
Fix the following arm-ttk unit test issue:
- API version 2019-06-01 of Microsoft.Network/networkSecurityGroups is 738 days
=> parameterize and upgrade api version

ihs/src/main/scripts/virtualimage.properties
This is required as part of solution to address https://github.com/WASdev/azure.websphere-traditional.cluster/issues/48.
- Add WAS_ND_INSTALL_DIRECTORY property to IHS virtualimage.properties with the same value as DMgr, see the 2nd note from Ranjan's comment in https://github.com/WASdev/azure.websphere-traditional.cluster/issues/48#issuecomment-867191495.
=> Add WAS_ND_INSTALL_DIRECTORY property to IHS virtualimage.properties

.github/workflows/ihsBuild.yml, .github/workflows/twas-ndBuild.yml
The **'-start'** param(Run waagent as a background process) of deprovision command'waagent -deprovision+user -force -start' will cause the deprovision **NOT EXECUTE** via ssh calls, so it needs to be removed.
Verified on forked repo by manually ssh to the VMs deployed using generated images to see if the user related data is removed.
twas-nd: https://github.com/zhengchang907/azure.websphere-traditional.image/runs/2929156017?check_suite_focus=true
ihs: https://github.com/zhengchang907/azure.websphere-traditional.image/actions/runs/978035653
Signed-off-by: Zheng Chang <zhengchang@microsoft.com>
=> Remove '-start' of deprovision command to fix timing issue

.github/workflows/ihsBuild.yml, .github/workflows/twas-ndBuild.yml, README.md, config.properties, ihs/README.md, ihs/pom.xml, ihs/src/main/arm/mainTemplate.json, ihs/src/main/resources/marketing-artifacts/README.md, twas-nd/README.md, twas-nd/pom.xml, twas-nd/src/main/arm/mainTemplate.json, twas-nd/src/main/resources/marketing-artifacts/README.md
The PR is to upgrade RHEL version of the base images from 8_3 to 8_4, which resolves the following issues:
* Fix WASdev/azure.websphere-traditional.cluster/issues/88
* Fix WASdev/azure.websphere-traditional.cluster/issues/89
* [Improve robustness of the pipeline](https://github.com/majguo/azure.websphere-traditional.image/pull/4)
The following test cases are passed using the private VM images generated by the source branch of the PR:
* Successfully deployed a static cluster with 1 worker node and 1 IHS, using the entitled IBM ID. Verified that the cluster and IHS works by visiting the installed `DefaultApplication` using IP address of IHS VM.
* Successfully deployed a dynamic cluster with 1 worker node and 1 IHS, using the entitled IBM ID. Verified that the cluster and IHS works by …
=> Upgrade to rhel 8_4

ihs/README.md, ihs/pom.xml, ihs/src/main/cli/deploy.azcli, twas-nd/README.md, twas-nd/pom.xml, twas-nd/src/main/cli/deploy.azcli
With pull request Azure/azure-javaee-iaas#20 is merged, it's time to move utility scripts that're not part of deployment scripts included in the offer to `src/main/cli` for better organization of code structure.
=> Move utility scripts to src/main/cli

ihs/pom.xml, ihs/src/main/scripts/virtualimage.properties, ihs/src/main/scripts/was-check.sh, twas-nd/pom.xml, twas-nd/src/main/scripts/virtualimage.properties, twas-nd/src/main/scripts/was-check.sh
This is the 1st PR to address WASdev/azure.websphere-traditional.cluster/issues/105.
The 2nd PR opened in cluster repo is https://github.com/WASdev/azure.websphere-traditional.cluster/pull/106.
* Add timestamps for entitlement check and was update
* Move hard-coded values to properties file
See section **Testing** from [the 2nd PR](https://github.com/WASdev/azure.websphere-traditional.cluster/pull/106) mentioned above.
=> Add timestamps for entitlement check and WAS installation update

config.properties, ihs/src/main/arm/mainTemplate.json, twas-nd/src/main/arm/mainTemplate.json
This PR is to resolve the following issues:
* Fix WASdev/azure.websphere-traditional.cluster/issues/109
* Add new property `datadisk.sizeGB`
* Reference data disk size from config file
The following test cases have been passed before opening the above two PRs:
* Successfully created twas-nd and ihs private VM images based on image repo;
* Successfully created a tWAS cluster (1 dmgr, 1 worker node & 1 IHS) by referencing the private images with an entitled IBMid. 
* User can then successfully deploy a default application `DefaultApplication` to the cluster and IHS, which is accessible later;
* Created an empty tWAS cluster (1 dmgr, 1 worker node & 1 IHS) by referencing the private images with an invalid IBMid.
* SSH into VMs and verified that WAS installation is removed from all VMs
* …
=> Use an appropriate size for data disk in the base images

.github/workflows/ihsBuild.yml, .github/workflows/twas-ndBuild.yml
The `azure-javaee-iaas` was updated before but the commit hash referenced in the workflow is not updated, which failed the pipeline run. Updating commit hash should fix the issue.
=> Update commit hash for azure-javaee-iaas

.github/workflows/ihsBuild.yml, .github/workflows/twas-ndBuild.yml, ihs/pom.xml, twas-nd/pom.xml
The PR is to resolve WASdev/azure.websphere-traditional.cluster/issues/126 by upgrading version of az cli.
The fix is tested and verified, see https://github.com/majguo/azure.websphere-traditional.image/runs/4515945537?check_suite_focus=true 
=> Fix pipeline failure of `azure.websphere-traditional.image`

README.md, twas-base/README.md, twas-base/pom.xml, twas-base/src/main/arm/mainTemplate.json, twas-base/src/main/arm/parameters.json, twas-base/src/main/cli/deploy.azcli, twas-base/src/main/scripts/install.sh, twas-base/src/main/scripts/virtualimage.properties, twas-base/src/main/scripts/was-check.sh
This PR is to address the following issues:
* resolve WASdev/azure.websphere-traditional.singleserver/issues/1
* Implement an ARM template to install a RHEL 8.4 VM on Azure with tWAS base and IBM Java JDK installed
* Implement cloud-init script to do entitlement check and upgrade
* Add entitlement check in `install.sh` to fail fast if the user account is unentitled
The following cases have already been verified before sending out the PR:
* Successfully deployed a RHEL 8.4 VM on Azure where with tWAS base and IBM Java JDK installed:
* Installed com.ibm.websphere.BASE.v90_9.0.5010.20211108_1200 to the /datadrive/IBM/WebSphere/Base/V9/ directory.
* Installed com.ibm.java.jdk.v8_8.0.7000.20211025_1430 to the /datadrive/IBM/WebSphere/Base/V9/ directory. 
* Successfully created a private image …
=> ARM template to deploy a VM installed with tWAS base edition

.github/workflows/ihsBuild.yml, .github/workflows/twas-baseBuild.yml, .github/workflows/twas-ndBuild.yml, twas-base/test/mainTemplate.json
The PR is to resolve WASdev/azure.websphere-traditional.singleserver/issues/2 which:
* Invoke the arm template to deploy a RHEL 8.4 VM with tWAS base pre-installed
* Create a private image from the VM
* Verify the VM deployed from the private image for the un-entitled user has no tWAS base installed
* Verify the VM deployed from the private image for the entitled user has tWAS base installed
* Generate disk SAS URLs for both OS and data disks
* Upload the text file including disk SAS URLs to output of the build
See the [successful build](https://github.com/majguo/azure.websphere-traditional.image/runs/4591303312?check_suite_focus=true) in the fork.
* Note: ignore failed job `summary` as it tried to interact with `WASdev` repo where the pipeline doesn't exist, before this PR is merged. …
=> Setup cicd pipeline for base image of twas single server

.github/workflows/ihsBuild.yml, .github/workflows/twas-baseBuild.yml, .github/workflows/twas-ndBuild.yml, README.md, ihs/src/main/scripts/virtualimage.properties, ihs/src/main/scripts/was-check.sh, twas-base/src/main/scripts/virtualimage.properties, twas-base/src/main/scripts/was-check.sh, twas-nd/src/main/scripts/virtualimage.properties, twas-nd/src/main/scripts/was-check.sh
The PR is to resolve WASdev/azure.websphere-traditional.cluster/issues/144 by changing the base image to support both entitlement and evaluation usages:
- If `customData` (input of `cloud-init`) has an valid format of IBMid credential, do entitlement check and iFixes installation as before.
- Otherwise it will be recognized as evaluation usage, neither the entitlement check nor the iFixes will be applied.
The pipeline is also enhanced to test evaluation feature of `twas-nd`, `ihs` and `twas-base` images.
The pipelines ran successfully on feature branch (ignore failed job `summary` as it needs to run WASdev repo instead of fork):
* [twas-base CICD](https://github.com/majguo/azure.websphere-traditional.image/actions/runs/1891676423)
* [ihs …
=> Support both entitlement and evaluation

docs/howto-access-source-vm.md, docs/howto-cleanup-after-image-published.md
This PR is a follow-up PR for #59, which adds a similar guide about how to clean up the storage account with VHD files for image creation after image is successfully published and available in Partner Center. 
=> Guide about how to cleanup after image is published

.github/workflows/ihsBuild.yml, .github/workflows/twas-baseBuild.yml, .github/workflows/twas-ndBuild.yml, ihs/test/check.sh, ihs/test/mainTemplate.json, twas-base/test/check.sh, twas-base/test/mainTemplate.json, twas-nd/test/check.sh, twas-nd/test/mainTemplate.json
The PR is to fix WASdev/azure.websphere-traditional.cluster/issues/163 which complains the intermittent failure of base image building pipelines.
The failure happened when the pipeline tried to execute the following command remotely in the VM using `ssh`:
```
result=$(sshpass -p ${{ env.vmAdminPassword }} -v ssh -p 22 -o StrictHostKeyChecking=no -o ConnectTimeout=100 -v -tt ${{ env.vmAdminId }}@${entitledVMIP} '(tail -n1) </var/log/cloud-init-was.log')
```
Per investigation and testing, the root cause is most probably that too many ssh connections are initiated in a short time window in [while loops](https://github.com/WASdev/azure.websphere-traditional.image/blob/main/.github/workflows/twas-baseBuild.yml#L249-L272).
The PR is to get rid of these ssh connections by moving the verification …
=> Fix intermittent failure of base image building pipelines

ihs/src/main/resources/marketing-artifacts/partner-center.html, twas-base/src/main/resources/marketing-artifacts/partner-center.html, twas-nd/src/main/resources/marketing-artifacts/partner-center.html
This PR has updates for partner-center.html files for the following VM image offerings.
Refer to the [slack messages](https://ibm-cloud.slack.com/archives/G010BB252NA/p1677206297444609) for comments.
1. Base
2. ND
3. IHS
I have used following links for VM images at the bottom of each partner-center.html. I am not sure how these links get created.
```
<li><a href="https://ibm.biz/twas-nd-portal">WebSphere ND Image on Azure VM</a></li>
<li><a href="https://ibm.biz/twas-base-portal">WebSphere Base Image on Azure VM</a></li>
<li><a href="https://ibm.biz/twas-ihs-portal">WebSphere IHS Image on Azure VM</a></li>
```
Also, I see the partner-center.html files referring to [IBM WebSphere Product Family on Azure](https://ibm.biz/WebSphereOnAzureContactMe) ; this link should also include VM image …
=> BVN: Azure WAS VM image partner-center.html updates

ihs/pom.xml, ihs/src/main/arm/mainTemplate.json, ihs/src/main/scripts/install.sh, ihs/src/main/scripts/welcome.motd, twas-base/pom.xml, twas-base/src/main/arm/mainTemplate.json, twas-base/src/main/scripts/install.sh, twas-base/src/main/scripts/welcome.motd, twas-nd/pom.xml, twas-nd/src/main/arm/mainTemplate.json, twas-nd/src/main/scripts/install.sh, twas-nd/src/main/scripts/welcome.motd
@git4rk made a good suggestion in the slack thread:
> We have to make sure instructions are clear to avoid any customer case. Can we display a message when customer logs into the VM?
This PR is to address the request by displaying a welcome message after a successful ssh login, including the necessary instructions about how to do further configuration after switching to root with `sudo -i`.
Workflow for each pipeline ran successfully:
* [twas-nd CICD](https://github.com/majguo/azure.websphere-traditional.image/actions/runs/4489260794)
* [ihs CICD](https://github.com/majguo/azure.websphere-traditional.image/actions/runs/4489261816)
* [twas-base CICD](https://github.com/majguo/azure.websphere-traditional.image/actions/runs/4489262684)
See the sample welcome message in the red box from the …
=> Display welcome message with instructions after successful ssh login

.github/workflows/twas-baseBuild.yml
@majguo  wrote:
> Meanwhile, the revert for twas-base in https://github.com/WASdev/azure.websphere-traditional.image/pull/75 hasn't covered everything needs to be reverted, so [twas-base CICD](https://github.com/WASdev/azure.websphere-traditional.image/actions/runs/4835898187) still failed. You need make further changes by referring to successful reverts for twas-nd or ihs, and re-run twas-base cicd.
> As a result, instead of fixing the revert of twas-base pipeline, we can also add back the automatic publish to the pipelines after re-publishing V2 release of the action. Pls make the call and take relative actions. (edited)
This commit completes the revert.  Thanks Jianguo.
=> On branch edburns-msft-ibm-247-revert-use-of-automatic-publishing-02

docs/howto-update-image.md
modified:   docs/howto-update-image.md
- in the instructions I see `Increment the version of twas-base/pom.xml.` but not for twas-nd and twas-ihs pom.xml update.
- Oh, that's a mistake in the doc. The correct link should be https://github.com/WASdev/azure.websphere-traditional.image/actions
=> On branch edburns-msft-ibm-342-end-to-end-automation-documentation

docs/howto-update-image.md
modified:   docs/howto-update-image.md
> I think you don't need run script to setup secrets if the repos already have them. @edburns documented the guide and he may know more details. (edited)
> @majguo is correct, the scripts are preconditions, so once the preconditions have been met, they stay met. I'll update the guidance to make that more clear.
=> On branch edburns-msft-clarify-preconditions

.github/workflows/ihsBuild.yml, .github/workflows/twas-baseBuild.yml, .github/workflows/twas-ndBuild.yml, docs/howto-update-image.md
- https://github.com/WASdev/azure.websphere-traditional.singleserver/issues/93
- https://github.com/WASdev/azure.websphere-traditional.cluster/issues/234
modified:   .github/workflows/ihsBuild.yml
modified:   .github/workflows/twas-ndBuild.yml
- When calling out to the cluster repository to run the integration-test workflow, assume you want to run the workflow on a branch named the same as the current branch.
modified:   docs/howto-update-image.md
- Add troubleshooting section.
- Create sub-section to break the tWAS ND (aka cluster) Azure Application offer into 1. VMs 2. Azure Application.
- Create sub-section to break the tWAS ND (aka cluster) Azure Application offer into 1. VMs 2. Azure Application.
=> Changes to this repo to fix the cross-repo spanning problems described in the following issues.

.github/workflows/ihsBuild.yml, .github/workflows/twas-baseBuild.yml, .github/workflows/twas-ndBuild.yml, docs/howto-update-image.md
1. Rename testResourceGroup with pattern: `${prefix}-${{ github.repository_owner }}-${{ github.run_id }}-${{ github.run_number }}`
1. Refactor workflows to ensure at the end of the workflow, the azure resources will be deleted.
2. Make [imageVersionNumber ](https://github.com/WASdev/azure.websphere-traditional.image/pull/105/files#diff-d3b6f66387b4f43de178e32bab5b0dcc786385e24a847110f40484d4e3a3f121R11) optional, the [sas_url ](https://github.com/WASdev/azure.websphere-traditional.image/blob/815375f05f4577e681492318376acabd048da760/.github/workflows/ihsBuild.yml#L314)will not be updated if it is empty.
3. Delete all resources if the image verification [fails](https://github.com/WASdev/azure.websphere-traditional.image/blob/815375f05f4577e681492318376acabd048da760/.github/workflows/ihsBuild …
=> Ensure workflow delete resources

.github/workflows/ihsBuild.yml, .github/workflows/twas-baseBuild.yml, .github/workflows/twas-ndBuild.yml, ihs/README.md, ihs/pom.xml, twas-base/README.md, twas-base/pom.xml, twas-nd/README.md, twas-nd/pom.xml
This pull request includes changes to the GitHub workflows and Maven configuration for the `ihs`, `twas-base`, and `twas-nd` projects, with the aim of simplifying the build process and improving the handling of dependencies. The most important changes are the removal of certain environment variables and checkout steps from the workflows, the addition of a new condition for deleting the `testResourceGroup`, and the addition of instructions for setting up local builds and repositories in the Maven configuration.
Changes to GitHub workflows:
* `.github/workflows/ihsBuild.yml`, `.github/workflows/twas-baseBuild.yml`, `.github/workflows/twas-ndBuild.yml`: 
* Removed the `refArmttk` and `refJavaee` environment variables and the steps to checkout `azure-javaee-iaas` and `arm-ttk`. 
* Instead, …
=> Remove azure javaee in workflows

config.properties
The certification failure report asks to apply [Red Hat security advisory RHSA-2024:2394](https://access.redhat.com/errata/RHSA-2024:2394), which is issued on `2024-04-30` and impacts Red Hat Enterprise Linux for x86_64 9 as well. For tWAS related vm image, it uses RHEL 9 as the base image, so we should update to a version of RHEL 9 vm image which includes the patch.
The PR is to update RHEL image to `9_4`, which seems updated on `2024-05-06` and should include the required patch `RHSA-2024:2394`:
|Architecture|    Offer|                     Publisher|      Sku|                              Urn        |                                                                Version| |
|--------------|------------------------|--------------|-------------------------------|--------------------------- …
=> Fix vm image certification failures

.github/workflows/ihsBuild.yml, .github/workflows/twas-baseBuild.yml, .github/workflows/twas-ndBuild.yml
The PR is to fix the issue detected in https://github.com/WASdev/azure.websphere-traditional.singleserver/actions/runs/10824397307/job/30031567803:
Learn more: https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/.
* https://github.com/WASdev/azure.websphere-traditional.singleserver/pull/107
* https://github.com/WASdev/azure.websphere-traditional.cluster/pull/256
=> Update to actions/upload-artifact@v4

.github/workflows/ihsBuild.yml, .github/workflows/twas-baseBuild.yml, .github/workflows/twas-ndBuild.yml, .github/workflows/update-vm-offer.yml
Reference to new released version [v3.2](https://github.com/microsoft/microsoft-partner-center-github-action/releases/tag/v3.2) for `microsoft/microsoft-partner-center-github-action` which fixed the issue that VM offer failed to be updated in partner center due to the incorrect domain name for schema uri of Product Ingestion API.
Test: https://github.com/azure-javaee/azure.websphere-traditional.image/actions/runs/13213374955
* **NOTE**: it's just for testing purpose, the new version added by the test has already been manually deleted after the test verification is done.
=> Update to version of `microsoft/microsoft-partner-center-github-action` to `v3.2`

.github/workflows/ihsBuild.yml, .github/workflows/twas-baseBuild.yml, .github/workflows/twas-ndBuild.yml, twas-nd/src/main/scripts/virtualimage.properties
The PR applies the similar workaround from #61, which update the repository url of twas-nd from `https://www.ibm.com/software/repositorymanager/entitled` to `http://www.ibm.com/software/repositorymanager/V9WASND`, in order to address the issue captured in [twas-nd CICD · azure-javaee/azure.websphere-traditional.image@2f96c87](https://github.com/azure-javaee/azure.websphere-traditional.image/actions/runs/13233476612/job/36934300089).
The additional enhancement is to use `--fail` option in curl command so that it fails fast if the singleserver/cluster integration test fails to be triggered with http errors.
Workflow run succeeded: https://github.com/majguo/azure.websphere-traditional.image/actions/runs/13241864914
=> Update twas-nd installation repository url

.github/workflows/ihsBuild.yml, .github/workflows/twas-baseBuild.yml, .github/workflows/twas-ndBuild.yml
This pull request includes updates to several GitHub Actions workflow files to add a new `location` parameter in the request data. 
Changes to GitHub Actions workflows:
* [`.github/workflows/ihsBuild.yml`](diffhunk://#diff-d3b6f66387b4f43de178e32bab5b0dcc786385e24a847110f40484d4e3a3f121L228-R228): Added the `location` parameter to the `requestData` in the integration tests trigger.
* [`.github/workflows/twas-baseBuild.yml`](diffhunk://#diff-bfa8815a785fb158eebfabeae46b703fd9f6b292d12cbb672e6dbe85a4fdd0f4L216-R216): Added the `location` parameter to the `requestData` in the image verification step.
* [`.github/workflows/twas-ndBuild.yml`](diffhunk://#diff-7cbf9c51c350c81d48c4dc8cf71f2deb121795bedf1fb700e2d03e7a62b3f95eL217-R217): Added the `location` parameter to the `requestData` in the …
=> CICD pipeline enhancements

.github/workflows/ihsBuild.yml, .github/workflows/twas-baseBuild.yml, .github/workflows/twas-ndBuild.yml
The PR is to fix issue of vm image publishing observed in partner center: `The source blob content is still undergoing modification`.
Testing:
* [twas-nd CICD](https://github.com/majguo/azure.websphere-traditional.image/actions/runs/13764526680)
* [ihs CICD](https://github.com/majguo/azure.websphere-traditional.image/actions/runs/13760370041)
* [twas-base CICD](https://github.com/majguo/azure.websphere-traditional.image/actions/runs/13759272205)
=> Delete source vm before updating vm offer with storage blobs

ihs/src/main/scripts/was-check.sh, twas-base/src/main/scripts/was-check.sh, twas-nd/src/main/scripts/was-check.sh
This pull request includes changes to several scripts related to WebSphere installation checks. The main change involves removing the deletion of the `virtualimage.properties` file. The reason behind is that `/datadrive/virtualimage.properties` shouldn't be removed in cloud-init as it's accessed by vm extension asynchronously. This corner case is captured by [twas-base CICD #70](https://github.com/WASdev/azure.websphere-traditional.image/actions/runs/13791848447/job/38576113611).
Changes to WebSphere installation scripts:
* [`ihs/src/main/scripts/was-check.sh`](diffhunk://#diff-15ff380841704bac45665515b268c84afcd3e30b4975c62c3d27371ff2913dd2L59-R59): Removed the deletion of the `virtualimage.properties` file during the WebSphere uninstall process.
* …
=> Fix issue `/datadrive/virtualimage.properties: No such file or directory`

.github/workflows/ihsBuild.yml, .github/workflows/twas-baseBuild.yml, .github/workflows/twas-ndBuild.yml, config.properties
Per @venunathb's testing and [RHSA-2025:3407](https://access.redhat.com/errata/RHSA-2025:3407), the `freetype` library installed in the current VM image has no patch for `CVE-2025-2736`:
```
yum list installed | grep freetype
freetype.x86_64                               2.10.4-9.el9                  @anaconda
```
This pull targets to fix `CVE-2025-2736` by upgrading REHL of vm base image to `9_5`. Additionally, it also includes changes to the GitHub Actions workflows by adding new input parameters to control the retention of testing VMs and updating offer artifacts, as well as conditional logic to handle these new inputs.
Update to configuration:
* [`config.properties`](diffhunk://#diff-763a89c2f6334284dbcf4ae81f31fec29a9093ceb6628fe39a930f1aa0feb9d5L17-R17): Updated the `image.sku` from …
=> Upgrade REHL of vm base image to `9_5` to fix `CVE-2025-27363`

.github/workflows/ihsBuild.yml, .github/workflows/twas-baseBuild.yml, .github/workflows/twas-ndBuild.yml, utilities/oscap.sh
This pull request includes the fix for SCAP scan reporting. It also updates workflow files by not  removing resource group for troubleshooting vm image generation issue. Below is a summary of the most important changes grouped by theme:
* Updated `oscap.sh` to remove the `--report` option from SCAP compliance scan commands to address a potential issue with report generation. Reports are now generated separately using the `oscap xccdf generate report` command. [[1]](diffhunk://#diff-42e04a5cb5612dd09b0e0a645a2838cf173d34f8f445f5d664fdfe0e39a4f183L27-R27) [[2]](diffhunk://#diff-42e04a5cb5612dd09b0e0a645a2838cf173d34f8f445f5d664fdfe0e39a4f183L37-R49)
* Added a workaround to resolve a known issue with `libxslt` causing segmentation faults during report generation. This includes uninstalling …
=> Fix the issue that fails to export html report for oscap
